### ISSUE TITLE
postcards material

### ISSUE THREAD

**Issue by lcolladotor** [lcolladotor/rnaseq_LCG-UNAM_2024#2]
@Melii99 please update https://lcolladotor.github.io/rnaseq_LCG-UNAM_2024/introducci%C3%B3n-a-r-y-rstudio.html#actividad-postcards as you see fit. Aka, edit https://github.com/lcolladotor/rnaseq_LCG-UNAM_2024/blob/50b261e4acd6b05bd912e016dbb064f6db312bcb/01_intro_rstudio.Rmd#L239 and below

**Comment by Melii99** [comment]
I edited the rnaseq_LCG-UNAM_2024/01_intro_rstudio.Rmd file to add the content into the GitHub page and linked the activity repository, which contains the used images, the original files, the web page and presentation.
